<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Extensions\" />
    <Folder Include="Services\" />
    <Folder Include="Interfaces\" />
    <Folder Include="Handlers\" />
    <Folder Include="EventBus\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DevWiki.EventDriven.Shared\DevWiki.EventDriven.Shared.csproj" />
  </ItemGroup>

</Project>
